# версия Python для проверки совместимости
target-version = "py311"
line-length = 120

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]
"parser.py" = ["C901"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]

[[tool.mypy.overrides]]
module = "async_pymongo"
ignore_missing_imports = true
disable_error_code = ["union-attr"]